UWPCE-PythonCert-ClassRepos/GP_Python210B_Winter_2019

- .gitignore
- students/paul_c/README.md
- students/paul_c/session01/break_me.py
- Added a personal directory under students and included a readme file.
- Added an entry in gitignore to avoid pushing .idea files.
> Added personal directory. Modified gitignore.

- students/jesse_miller/session01/break_me.py
Adding my Error python script for Session 1
> session1 exercise break_me.py

- students/douglas_klos/README.rst
- students/douglas_klos/session1/break_me.py
> Added student folder, readme file, and session1 break_me.py

- .idea/Intro_Class.iml
- .idea/encodings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/workspace.xml
- students/jeff_shabani/README.MD
- students/jeff_shabani/session01/break_me.py
- students/jeff_shabani/session01/codingbat_sum13.py
Please review my solution to CodingBat exercise sum13 from the List 2 group. While it works I think there must be a more efficient way to achieve the same result. Below is the description of the exercise:
Return the sum of the numbers in the array, returning 0 for an empty array. Except the number 13 is very unlucky, so it does not count and numbers that come immediately after a 13 also do not count
.sum13([1, 2, 2, 1]) → 6
sum13([1, 1]) → 2
sum13([1, 2, 2, 1, 13]) → 6
--
> Lesson 1 - CodingBat sum13 exercise

- students/elaine_x/session02/Fizzbuzz_ex.py
- students/elaine_x/session02/gridprinter_ex.py
- students/elaine_x/session02/series_ex.py
gridprinter_ex.py
Fizzbuzz_ex.py
series_ex.py
> submitting session02 exercises (3)

- students/douglas_klos/session3/list_lab.py
- students/douglas_klos/session3/slice_lab.py
- students/douglas_klos/session3/strformat_lab.py
Here are my session 3 exercises.  I'd appreciate any feedback on these, potential errors, areas that can be improved, or suggestions.  I'm having some (hopefully simple) surgery tomorrow (Friday) and likely won't be doing as much while recovering.
Thanks.
> Session 3 exercises for review

- students/jesse_miller/session03/mailroom.py
- students/jesse_miller/session04/dict_lab.py
I don't know if it's graded or not, but if so, my mail_menu() that's commented out, causes main() to loop back to main() if you type send.  I cannot figure out why.  Everything else works though.
> mailroom.py

- .gitignore
- students/ScottL/session03/Mailroom_Part1.py
- students/ScottL/session03/SlicingLab.py
- students/ScottL/session03/list_lab.py
- students/ScottL/session03/strformat_lab.py
Lesson 3 Assignment Files:
- Mailroom, Part 1
- Slicing Lab
- String Formatting Lab
- List Lab
> Adding lesson 3 assignment files

- students/WooseokJ/List+WJ.py
- students/WooseokJ/Mail+part1+WJ+.py
- students/WooseokJ/Slicing+WJ.py
- students/WooseokJ/String+WJ.py
having a bit of problem with the List Exercise where the computer would freeze upon loading causing the delay in submission cause i had to fix my computer first
> Adding for Lesson 3

- students/ScottL/session04/Mailroom_Part2.py
- students/ScottL/session04/Trigrams.py
> Session 4 assignment submission

- students/daniel_carrasco/session03/mailroom.py
I was asked to resubmit lesson 3 mailroom. I decided to make it different from lesson 4 mailroom since I didn't know about dictionary switching so I used if, elif, else for my menu. I kept the donors list as a dictionary since I knew how to use dictionaries before I started this class.
Thank you for letting me resubmit.
> resubmitting for mailroom lesson 3 regrade.

- students/marsha_w/lesson_04/mailroom2.py
- students/marsha_w/lesson_04/trigrams.py
I am resending this pull request.
> adding lesson04 for review

- students/jesse_miller/session05/except_exercise.py
- students/jesse_miller/session05/mailroom.py
> Completed exceptions exercise

- students/jeff_shabani/session01/break_me.py
- students/jeff_shabani/session05/except_exercise.py
- students/jeff_shabani/session05/mailroom_3.py
Hello, this is my pull request for the except_exercise.
> Except excercise

- students/ScottL/session05/Mailroom_Part3.py
- students/ScottL/session05/except_exercise.py
- students/ScottL/session05/except_test.py
- Exception Exercise (along with Exception Test)
- Mailroom, Part 3.  Several Try/Except blocks were added but I didn't see a good place to use a list comprehension.  The few simple 'for' blocks in my code called the print function, which as explained in the text, is not an appropriate place to use a list comprehension.  Please let me know if you'd like me to re-arrange code to demonstrate use of list comprehensions.
> Lesson05 Assignments

- students/douglas_klos/session5/mailroom3.py
- students/douglas_klos/session6/mailroom4.py
- students/douglas_klos/session6/test_mailroom4.py
Try / Except statements for error trapping bad user input and when trying to write to directories without permission.
I'm not sure where I'd use comprehensions in this code.  Before using a dictionary there were a couple I had used, but removed them after adding dicts.  If there's a place that they could be used in this I'm open to suggestions but
> Session5, mailroom3, try/except

- students/alex_whitty/session02/fizzbizz.py
- students/alex_whitty/session02/grid_func.py
- students/alex_whitty/session02/grid_printer.py
- students/alex_whitty/session02/print_grid2.py
- students/alex_whitty/session02/series.py
- students/alex_whitty/session03/list_lab_series1.py
- students/alex_whitty/session03/list_lab_series2.py
- students/alex_whitty/session03/list_lab_series3.py
- students/alex_whitty/session03/list_lab_series4.py
- students/alex_whitty/session03/mailroom.py
- students/alex_whitty/session03/slicing_lab.py
- students/alex_whitty/session03/strformat_lab.py
- students/alex_whitty/session04/double_take.txt
- students/alex_whitty/session04/mailroom2.py
- students/alex_whitty/session04/trigrams.py
- students/alex_whitty/session05/except_exercise.py
- students/alex_whitty/session05/except_test.py
- students/alex_whitty/session05/mailroom3.py
Hello Luis,
I have completed the fixes on mailroom.py for review.
> Completed fixes on Session03\mailroom.py

- students/paul_c/session05/mailroom.py
Try blocks were added to the main and add_donation functions to prompt users to try again if they input bad data. I decided not to add a try block to the send_thankyou function because any unknown data would be received as a new donor name.
I had a hard time figuring out if I needed to use any comprehensions. The only time I generate a sequence from another sequence is in the send_all and create_report functions. In these functions a string is generated from iterating though a dictionary. I tried some things but I couldn't really figure out how to do a string comprehension out of a dictionary.
Please let me know if I missed the point of the assignment. I'll go back and add comprehensions if desired.
> Add try blocks to mailroom

- students/mjchang/session05/except_exercise.py
- students/mjchang/session05/except_test.py
This was a fun way to track down exceptions (perhaps because it was someone else's code!)
> adding except_exercise

- students/alex_whitty/session06/mailroom4.py
- students/alex_whitty/session06/test_mailroom.py
Hello Luis/Michael, 
Having issues testing my code(mailroom4, test_mailroom4) seems to me refactor produces more errors when unit testing while using the unittest framework. Should I be able to test the code as is successfully before refactoring or do I have it backward? 
Thanks,
Alex
> Need code review

- students/jeff_shabani/session06/test_mailroom_4.py
I added two get_value tests here: one that passes and one expected failure.
> teste mailroom_4 - added get_value tests

- students/marsha_w/lesson_05/except_exercise.py
- students/marsha_w/lesson_05/except_test.py
- students/marsha_w/lesson_05/mailroom3.py
- students/marsha_w/lesson_06/mailroom4.py
- students/marsha_w/lesson_06/test_create_report.py
- students/marsha_w/lesson_06/test_email_report.py
- students/marsha_w/lesson_06/test_mailroom.py
- students/marsha_w/lesson_06/test_print_thankyou.py
Lesson06 scripts are ready for review
> Lesson06 scripts

- students/alex_whitty/session06/mailroom4.py
- students/alex_whitty/session06/test_mailroom.py
> Submitting Session06

- students/daniel_carrasco/session05/Art Bart_2019-02-17.txt
- students/daniel_carrasco/session05/Daniel Carrasco_2019-02-17.txt
- students/daniel_carrasco/session05/Harry Scary_2019-02-17.txt
- students/daniel_carrasco/session05/Hay Boo_2019-02-17.txt
- students/daniel_carrasco/session05/except_exercise.py
- students/daniel_carrasco/session05/except_test.py
- students/daniel_carrasco/session05/mailroom.py
- students/daniel_carrasco/session06/Art Bart_2019-02-24.txt
- students/daniel_carrasco/session06/Harry Scary_2019-02-24.txt
- students/daniel_carrasco/session06/Hay Boo_2019-02-24.txt
- students/daniel_carrasco/session06/mailroom.py
- students/daniel_carrasco/session06/test_mailroom.py
- students/jesse_miller/README.rst
Week 5 assignment. I think this went pretty well. I couldn't add any list comprehension to my mailroom but I can change my code to make list. I do use for statements but that's to print not to make a list.
The exceptions exercise has really helpful, I never knew about this!
> lesson 5 assignment

- students/ScottL/session06/Mailroom_Part4.py
- students/ScottL/session06/test_Mailroom_Part4.py
- students/ScottL/session06/test_walnut_party.py
- students/ScottL/session06/walnut_party.py
Mailroom_Part4
I'm not sure if I set up all the tests as intended.  Let me know if I missed the mark a bit so I can make some adjustments.
> Module 6 files

- students/jeff_shabani/session06/mailroom_4.py
- students/jeff_shabani/session06/test_mailroom_4.py
- students/jeff_shabani/session07/html_render.py
- students/jeff_shabani/session07/run_html_render.py
- students/jeff_shabani/session07/sample_html.html
- students/jeff_shabani/session07/test_html_render.py
What did I do wrong to make this happen?
> My append method puts 'None' and the front of the string.

- students/alex_whitty/session07/html_render.py
- students/alex_whitty/session07/run_html_render.py
- students/alex_whitty/session07/sample_html.html
- students/alex_whitty/session07/test_html_render.py
> Updating Session07

- students/ScottL/session07/html_render.py
- students/ScottL/session07/run_html_render.py
- students/ScottL/session07/test_html_render.py
Better late than never I suppose
> Assignment07: HTML_Render, ScottL

- students/marsha_w/lesson_07/html_render.py
- students/marsha_w/lesson_07/run_html_render.py
- students/marsha_w/lesson_07/sample_html.html
- students/marsha_w/lesson_07/test_html_render.py
Reverts UWPCE-PythonCert-ClassRepos/GP_Python210B_Winter_2019#165
> Revert "Revert "lesson 07""

- students/elaine_x/session08/circle_exercise_ex.py
1. For step 5, how to create an alternative constructor using classmethod?
2. For step 7, c2 * 3 works. but what about 3 * c2 ? – how to fix that?
> session 08 Circle Class Question

- students/shirin_ak/Session08/Circle.py
- students/shirin_ak/Session08/test_Circle.py
Could you please check what I am missing here? My three test adding , multiplying and sorting circles keeps failing.
Thank you
> Code for Review

- students/ScottL/session08/circle_class.py
- students/ScottL/session08/test_circle_class.py
> Assignment 8 files

- students/daniel_carrasco/session08/circle.py
- students/daniel_carrasco/session08/test_circle.py
> Session 08

- students/alex_whitty/session06/mailroom4.py
- students/alex_whitty/session06/test_mailroom.py
- students/alex_whitty/session08/circle.py
- students/alex_whitty/session08/test_circle.py
Submitting session08 files(circle and test_circle).
> Submitting Session08 files
